version: '3'

vars:
  APP_NAME: "gssm"

includes:
  vendor: .github/taskfiles/vendor.yml
  build: .github/taskfiles/build.yml
  package: .github/taskfiles/package.yml

tasks:
  default:
    cmds: 
      - task --list-all
    silent: true