version: '3'

checksum: false

tasks:

  darwin:
    summary: Builds a `.app` bundle
    cmds:
      - mkdir -p {{.APP_NAME}}.app/Contents/{MacOS,Resources}
      - cp build/icons.icns {{.APP_NAME}}.app/Contents/Resources
      - cp build/bin/{{.APP_NAME}} {{.APP_NAME}}.app/Contents/MacOS
      - cp build/Info.plist {{.APP_NAME}}.app/Contents

  windows:

  all:
    summary: Builds the application
    cmds:
      - task: darwin
      - task: windows
      # - task: linux